version: "1"

services:
  testpage:
    image: ghcr.io/patrickmohr/abitmorehub:latest
    restart: always
    pull_policy: always
    ports:
      - 8080:8080

networks:
  default:
    external: true
    name: proxy